### ISSUE TITLE
1-2 slides demonstrating command line tool

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/exif#2]
Think we can get to this today/tomorrow? Going to be in SF next Tues-Thur!

**Comment by mattl** [comment]
[exif.pdf](https://github.com/creativecommons/exif/files/133461/exif.pdf)

**Comment by mattl** [comment]
![exif](https://cloud.githubusercontent.com/assets/33296/13095436/56161a36-d4d7-11e5-808e-006f675fa128.png)

**Comment by mattl** [comment]
![exif](https://cloud.githubusercontent.com/assets/33296/13119028/a8995792-d56c-11e5-8481-800ee0fded4c.png)
